version: '3.8'

# Áp dụng cho tất cả services
env_file:
  - .env

services:
  config-server:
    build: ./config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  eureka-server:
    build: ./eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  auth-service:
    build: ./auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Cả 3 biến DB cũng sẽ tự động load từ .env
      - DATABASE_URL=${AUTH_SERVICE_DB_URL}
      - DATABASE_USERNAME=${AUTH_SERVICE_DB_USERNAME}
      - DATABASE_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
    networks:
      - judge-net

  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=${USER_SERVICE_DB_URL}
      - DATABASE_USERNAME=${USER_SERVICE_DB_USERNAME}
      - DATABASE_PASSWORD=${USER_SERVICE_DB_PASSWORD}
    networks:
      - judge-net

  forum-service:
    build: ./forum-service
    ports:
      - "${FORUM_SERVICE_PORT}:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=${FORUM_SERVICE_DB_URL}
      - DATABASE_NAME=${FORUM_SERVICE_DB}
    networks:
      - judge-net

  problem-service:
    build: ./problem-service
    ports:
      - "${PROBLEM_SERVICE_PORT}:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=${PROBLEM_SERVICE_DB_URL}
      - DATABASE_NAME=${PROBLEM_SERVICE_DB}
    networks:
      - judge-net

  submission-service:
    build: ./submission-service
    ports:
      - "${SUBMISSION_SERVICE_PORT}:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=${SUBMISSION_SERVICE_DB_URL}
      - DATABASE_NAME=${SUBMISSION_SERVICE_DB}
      - JUDGE0_URL=${JUDGE0_URL}
      - JUDGE0_AUTH_TOKEN=${JUDGE0_AUTH_TOKEN}
    networks:
      - judge-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - auth-service
      - user-service
      - problem-service
      - submission-service
      - forum-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - API_PREFIX=${API_PREFIX}
      - HOSTNAME=${HOSTNAME}
    networks:
      - judge-net

networks:
  judge-net:
    driver: bridge
