services:
  config-server:
    build: ./config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - HOSTNAME=${HOSTNAME}
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - AUTH_SERVICE_DB_URL=${AUTH_SERVICE_DB_URL}
      - AUTH_SERVICE_DB_USERNAME=${AUTH_SERVICE_DB_USERNAME}
      - AUTH_SERVICE_DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
      - USER_SERVICE_DB_URL=${USER_SERVICE_DB_URL}
      - USER_SERVICE_DB_USERNAME=${USER_SERVICE_DB_USERNAME}
      - USER_SERVICE_DB_PASSWORD=${USER_SERVICE_DB_PASSWORD}
      - FORUM_SERVICE_DB_URL=${FORUM_SERVICE_DB_URL}
      - FORUM_SERVICE_DB=${FORUM_SERVICE_DB}
      - PROBLEM_SERVICE_DB_URL=${PROBLEM_SERVICE_DB_URL}
      - PROBLEM_SERVICE_DB=${PROBLEM_SERVICE_DB}
      - SUBMISSION_SERVICE_DB_URL=${SUBMISSION_SERVICE_DB_URL}
      - SUBMISSION_SERVICE_DB=${SUBMISSION_SERVICE_DB}
      - JUDGE0_URL=${JUDGE0_URL}
      - JUDGE0_AUTH_TOKEN=${JUDGE0_AUTH_TOKEN}
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - FORUM_SERVICE_PORT=${FORUM_SERVICE_PORT}
      - PROBLEM_SERVICE_PORT=${PROBLEM_SERVICE_PORT}
      - SUBMISSION_SERVICE_PORT=${SUBMISSION_SERVICE_PORT}
    networks:
      - judge-net

  eureka-server:
    build: ./eureka-server
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  auth-service:
    build: ./auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  user-service:
    build: ./user-service
    ports:
      - "${USER_SERVICE_PORT}:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  forum-service:
    build: ./forum-service
    ports:
      - "${FORUM_SERVICE_PORT}:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  problem-service:
    build: ./problem-service
    ports:
      - "${PROBLEM_SERVICE_PORT}:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  submission-service:
    build: ./submission-service
    ports:
      - "${SUBMISSION_SERVICE_PORT}:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - judge-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - auth-service
      - user-service
      - forum-service
      - problem-service
      - submission-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - API_PREFIX=${API_PREFIX}
      - HOSTNAME=${HOSTNAME}
    networks:
      - judge-net

networks:
  judge-net:
    driver: bridge
