spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
          routes:
            # AUTH ROUTE
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth-service/**
              filters:
                - RewritePath=/api/v1/auth-service/(?<path>.*), /${path}
            # USER ROUTE
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/user-service/**
              filters:
                - RewritePath=/api/v1/user-service/(?<path>.*), /${path}
            # FORUM ROUTE
            - id: FORUM-SERVICE
              uri: lb://FORUM-SERVICE
              predicates:
                - Path=/api/v1/forum-service/**
              filters:
                - RewritePath=/api/v1/forum-service/(?<path>.*), /${path}
            # PROBLEM ROUTE
            - id: PROBLEM-SERVICE
              uri: lb://PROBLEM-SERVICE
              predicates:
                - Path=/api/v1/problem-service/**
              filters:
                - RewritePath=/api/v1/problem-service/(?<path>.*), /${path}
server:
  port: ${API_GATEWAY_PORT}