spring:
  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
          routes:
            # BLOCK ALL INTERNAL ROUTES
            - id: BLOCK_INTERNAL
              uri: no://op
              order: -1
              predicates:
                - Path=/api/v1/**/internal/**
              filters:
                - SetStatus=403

            # AUTH ROUTE
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/login/**,/logout/**,/register/**,/forgot-password/**,/confirm-registration/**,/reset-password/**,/oauth2/**
              filters:
                - PreserveHostHeader
                - AddRequestHeader=X-Forwarded-Proto, http
                - AddRequestHeader=X-Forwarded-Host, localhost
                - AddRequestHeader=X-Forwarded-Port, 8080
                - StripPrefix=0
            
            # USER ROUTE  
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2  # Removes /api/v1/user-service
            
            # FORUM ROUTE
            - id: FORUM-SERVICE
              uri: lb://FORUM-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2  # Removes /api/v1/forum-service
            
            # PROBLEM ROUTE
            - id: PROBLEM-SERVICE
              uri: lb://PROBLEM-SERVICE
              predicates:
                - Path=/api/v1/problems/**
              filters:
                - StripPrefix=2  # Removes /api/v1/problem-service

            # SUBMISSION ROUTE
            - id: SUBMISSION-SERVICE
              uri: lb://SUBMISSION-SERVICE
              predicates:
                - Path=/api/v1/submissions/**
              filters:
                - StripPrefix=2  # Removes /api/v1/problem-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always