spring:
  data:
    mongodb:
      uri: ${FORUM_SERVICE_DB_URL}
      database: ${FORUM_SERVICE_DB}
      auto-index-creation: true

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"