spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${DOMAIN}/oauth2/jwks
          issuer-uri: ${DOMAIN}
  jpa:
    hibernate:
      ddl-auto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://user-mysql:3306/${USER_SERVICE_DB}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always