spring:
  jpa:
    hibernate:
      ddl-auto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${USER_SERVICE_DB_URL}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: ${USER_SERVICE_PORT}

eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    serviceUrl:
      defaultZone: http://${HOSTNAME}:${EUREKA_SERVER_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"