# config-server/src/main/resources/application.yml
spring:
  profiles:
    active: docker
  cloud:
    config:
      server:
        composite:
          - type: environment
          - type: native
            search-locations: classpath:/configurations

server:
  port: ${CONFIG_SERVER_PORT:8888}
