spring:
  profiles:
    active: native
  cloud:
    config:
      server:
         native:
            search-locations: file:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8888
