name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production
    env:
        # Common
        API_PREFIX:                 ${{ vars.API_PREFIX }}
        CLIENT_URL:                 ${{ vars.CLIENT_URL }}
        DEV_CLIENT_URL:             ${{ vars.DEV_CLIENT_URL }}

        # Auth service DB
        AUTH_SERVICE_DB:            ${{ secrets.AUTH_SERVICE_DB }}
        AUTH_SERVICE_DB_USERNAME:   ${{ secrets.AUTH_SERVICE_DB_USERNAME }}
        AUTH_SERVICE_DB_PASSWORD:   ${{ secrets.AUTH_SERVICE_DB_PASSWORD }}
        CLIENTID:                   ${{ secrets.CLIENTID }}
        CLIENT_SECRET:              ${{ secrets.CLIENT_SECRET }}
        GATEWAY_CLIENT_URL:         ${{ secrets.GATEWAY_CLIENT_URL }}
        AUTH_SERVER_URL:            ${{ secrets.AUTH_SERVER_URL }}

        # User service DB
        USER_SERVICE_DB:            ${{ secrets.USER_SERVICE_DB }}
        USER_SERVICE_DB_USERNAME:   ${{ secrets.USER_SERVICE_DB_USERNAME }}
        USER_SERVICE_DB_PASSWORD:   ${{ secrets.USER_SERVICE_DB_PASSWORD }}

        # Forum service DB
        FORUM_SERVICE_DB_URL:       ${{ secrets.FORUM_SERVICE_DB_URL }}
        FORUM_SERVICE_DB:           ${{ secrets.FORUM_SERVICE_DB }}

        # Problem service DB
        PROBLEM_SERVICE_DB_URL:     ${{ secrets.PROBLEM_SERVICE_DB_URL }}
        PROBLEM_SERVICE_DB:         ${{ secrets.PROBLEM_SERVICE_DB }}

        # Submission service DB & Judge0
        SUBMISSION_SERVICE_DB_URL:  ${{ secrets.SUBMISSION_SERVICE_DB_URL }}
        SUBMISSION_SERVICE_DB:      ${{ secrets.SUBMISSION_SERVICE_DB }}
        JUDGE0_ENDPOINT:            ${{ vars.JUDGE0_ENDPOINT }}
        JUDGE0_AUTH_TOKEN:          ${{ secrets.JUDGE0_AUTH_TOKEN }}

        # OAuth for Auth Service
        GOOGLE_CLIENT_ID:           ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET:       ${{ secrets.GOOGLE_CLIENT_SECRET }}

        # Mail credential for mail service
        MAIL_USERNAME:              ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD:              ${{ secrets.MAIL_PASSWORD }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build all services with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Save Docker Images as Artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            **/target/*.jar

      - name: Deploy with Docker Compose (optional, if self-hosted)
        run: docker-compose up -d